### PR TITLE
scroll into view

### LINKED ISSUE #43: Inner text node position should follow cursor position
To reproduce:

- `cargo run --example basic`
- Type `hello there`
- Press left-arrow repeatedly until the cursor disappears

This reveals another issue with the janky zero-width cursor setup when left-arrow is pressed for the first time.

Roughly, we need to
- Get the relative cursor position from `TextLayoutInfo`
- Offset the inner text node so that the cursor is always visible

Note that this is going to be janky when there are spaces involved until Bevy 0.15 due to https://github.com/bevyengine/bevy/issues/13063, and there's not much we can do about that.

### PR DESCRIPTION
**Pull request by robtfm**
fixes #43 

a bit more complex than i expected to get the behaviour to work well when typing in the middle or at the end

### CODE REVIEW

**Comment by rparrett** [comment]
Awesome, thanks for working on this.

Unfortunately, something doesn't seem to be working quite right.

https://github.com/user-attachments/assets/d3392f49-6033-430e-b1a7-822cf2f1e168

**Comment by robtfm** [comment]
weird, it works for me ...

https://github.com/user-attachments/assets/35eb17dd-7ffc-44d5-8298-6947d2891393

**Comment by rparrett** [comment]
Interesting. Still seeing the behavior after `cargo updating` to Bevy 0.14.1. So potentially something platform-specific or a hard-to-reproduce system ordering thing or something.

On my end, I do see the scrolling happen after one more left arrow press, but scrolling right again is a bit odd too:

https://github.com/user-attachments/assets/79e01174-b30f-4e50-96fe-74ad611e6c90

**Comment by robtfm** [comment]
I don’t think it can be system ordering as the update is based on `Changed<TextLayoutInfo>`. 

I’m on windows, what’s your platform?

**Comment by rparrett** [comment]
macOS

**Comment by rparrett** [comment]
Maybe it's a scale factor thing (I'm at 2.0)

**Comment by rparrett** [comment]
Yeah, that seems to be it. Look good with
```rust
.add_plugins(DefaultPlugins.set(WindowPlugin {
    primary_window: Some(Window {
        resolution: WindowResolution::default().with_scale_factor_override(1.0),
        ..default()
    }),
    ..default()
}))
```

**Comment by robtfm** [comment]
Ok thanks for investigating. I don’t have a Mac to test on but I would guess either multiplying or dividing the cursor pos (at ~417) would fix it, if you have a chance to try

**Comment by rparrett** [comment]
Seems to work well. The hoops we have to jump through to obtain the correct scale factor are pretty said, but nothing to be done about that.

Will try to remember to check if the scale factor thing is still an issue with the cosmic-text backend if the next Bevy release doesn't include a text input widget.

Thanks!

**Pull request merged**
