### PR TITLE
Fix backspace and enter in web builds

### LINKED ISSUE #2: wasm: backspace and enter don't work
`winit` doesn't send `ReceivedCharacter` events for these on the web.

So we need to use `KeyboardInput` events for these. This is unfortunate because the separate event streams can cause timing issues. In another project, to fix these timing issues, I resorted to using `KeyboardInput` for everything, but this came at the expense of easy international keyboard support.

So I think switching backspace and enter to `KeyboardInput` is the right call for now, potentially only for wasm if that doesn't complicate things too much.

This is fixed in winit 0.29 (and hopefully bevy 0.12. see https://github.com/bevyengine/bevy/pull/8745) where these two events are unified into `KeyEvent`.

### PR DESCRIPTION
**Pull request by rparrett**
Fixes #2

This comes with some caveats mentioned in that issue. If backspace/enter and another key arrive on the same frame, we have no way of knowing which one came first.

### CODE REVIEW

**Comment by werner291** [comment]
> If backspace/enter and another key arrive on the same frame, we have no way of knowing which one came first.

Does that really matter? This would practically mean the user mashing keys at the same time... Should they even expect coherent output?

**Comment by rparrett** [comment]
It's actually pretty easy to land two keystrokes in the same 16ms (60fps) period and it was a major problem for me in a typing game project.

I still think this is the right temporary solution.

**Comment by werner291** [comment]
Since it's a single line of input... Grabbing the character first like you're doing and then checking for key inputs seems like the right solution, since the user will likely want to hit "enter" to confirm input right after entering the last character of the line.

But yes, 16ms does sound like quite a timespan for things to get mixed up in.

**Comment by werner291** [comment]
Huh, these events really should come with timestamps so that you can order the different types relative to each other... oh well.

**Comment by rparrett** [comment]
Thanks for checking.

I'll do a release later today or tomorrow.

**Pull request merged**
